#pragma kernel Fow

Texture2D<float4> RT_Current;
RWTexture2D<float4> RT_Overlap;

[numthreads(8, 8, 1)]
void Fow(uint3 id : SV_DispatchThreadID)
{
    float4 currentPixel = RT_Current[id.xy];
    currentPixel = ceil(currentPixel);
    float4 overlapPixel = RT_Overlap[id.xy];

    RT_Overlap[id.xy] = max(currentPixel, overlapPixel);
}

#pragma kernel Blur

RWTexture2D<float4> RT_BlurOverlap; 
int BlurDetail;
[numthreads(8, 8, 1)]
void Blur(uint3 id : SV_DispatchThreadID)
{
    float4 sum = float4(0, 0, 0, 0);
    
    for (int x = -BlurDetail; x <= BlurDetail; x++)
    {
        for (int y = -BlurDetail; y <= BlurDetail; y++)
        {
            sum += RT_Overlap[id.xy + int2(x, y)];
        }
    }
    float length = BlurDetail * 2 + 1;
    float total = length * length;
    RT_BlurOverlap[id.xy] = sum / total;
}

#pragma kernel BlurCurrent

RWTexture2D<float4> RT_Current_RW;
RWTexture2D<float4> RT_BlurCurrent;

[numthreads(8, 8, 1)]
void BlurCurrent(uint3 id : SV_DispatchThreadID)
{
    float4 sum = float4(0, 0, 0, 0);
    for (int x = -BlurDetail; x <= BlurDetail; x++)
    {
        for (int y = -BlurDetail; y <= BlurDetail; y++)
        {
            sum += RT_Current_RW[id.xy + int2(x, y)];
        }
    }
    float length = BlurDetail * 2 + 1;
    float total = length * length;
    float4 blurred = sum / total;
    float4 original = RT_Current_RW[id.xy];
    
    float brightness = 2;

    // max()로 합친 후 밝기를 곱하고, saturate()로 안전하게 0~1 사이로 묶어줍니다.
    RT_BlurCurrent[id.xy] = saturate(max(blurred, original) * brightness);
}